version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: 'mongodb://mongo:27017/mydb'

  mongo:
    image: mongo:6.0.4
    restart: always
    ports:
      - '27018:27017'

